# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e29314668eff045d22117e33897428e5a41f3e37484529a9a38a3a296cd487f7b278598f66ebf0c3e779f1cb113db526f32e45ad9888ece279d67a6ac1fe8f57

test:
  secret_key_base: 446535babe609f016dd1e3babe7885e1b2b856a2cff8f4d4d2e8f150c88e90459c8914261a03224c38631bb4a7d1a0367845a0008a04314cb3ef4ac53811d6ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
